# GENERATED FILE: all modifications will be overwritten.

cdef extern from 'tidyenum.h' nogil:

    # Rationale: If Cython thinks the enums are T*, then it won't automagically convert to ints,
    #            so it's easier to find wrong type usage.

    ctypedef struct __Enum__TidyAttrId
    ctypedef struct __Enum__TidyAttrSortStrategy
    ctypedef struct __Enum__TidyConfigCategory
    ctypedef struct __Enum__TidyDoctypeModes
    ctypedef struct __Enum__TidyDupAttrModes
    ctypedef struct __Enum__TidyEncodingOptions
    ctypedef struct __Enum__TidyFormatParameterType
    ctypedef struct __Enum__TidyLineEnding
    ctypedef struct __Enum__TidyNodeType
    ctypedef struct __Enum__TidyOptionId
    ctypedef struct __Enum__TidyOptionType
    ctypedef struct __Enum__TidyReportLevel
    ctypedef struct __Enum__TidyTagId
    ctypedef struct __Enum__TidyTriState
    ctypedef struct __Enum__TidyUppercase
    ctypedef struct __Enum__TidyUseCustomTagsState
    ctypedef struct __Enum__tidyStrings

    ctypedef __Enum__TidyAttrId *TidyAttrId 'TidyAttrId'
    ctypedef __Enum__TidyAttrSortStrategy *TidyAttrSortStrategy 'TidyAttrSortStrategy'
    ctypedef __Enum__TidyConfigCategory *TidyConfigCategory 'TidyConfigCategory'
    ctypedef __Enum__TidyDoctypeModes *TidyDoctypeModes 'TidyDoctypeModes'
    ctypedef __Enum__TidyDupAttrModes *TidyDupAttrModes 'TidyDupAttrModes'
    ctypedef __Enum__TidyEncodingOptions *TidyEncodingOptions 'TidyEncodingOptions'
    ctypedef __Enum__TidyFormatParameterType *TidyFormatParameterType 'TidyFormatParameterType'
    ctypedef __Enum__TidyLineEnding *TidyLineEnding 'TidyLineEnding'
    ctypedef __Enum__TidyNodeType *TidyNodeType 'TidyNodeType'
    ctypedef __Enum__TidyOptionId *TidyOptionId 'TidyOptionId'
    ctypedef __Enum__TidyOptionType *TidyOptionType 'TidyOptionType'
    ctypedef __Enum__TidyReportLevel *TidyReportLevel 'TidyReportLevel'
    ctypedef __Enum__TidyTagId *TidyTagId 'TidyTagId'
    ctypedef __Enum__TidyTriState *TidyTriState 'TidyTriState'
    ctypedef __Enum__TidyUppercase *TidyUppercase 'TidyUppercase'
    ctypedef __Enum__TidyUseCustomTagsState *TidyUseCustomTagsState 'TidyUseCustomTagsState'
    ctypedef __Enum__tidyStrings *tidyStrings 'tidyStrings'

    const TidyAttrId N_TIDY_ATTRIBS
    const TidyAttrId TidyAttr_ABBR
    const TidyAttrId TidyAttr_ABOUT
    const TidyAttrId TidyAttr_ACCEPT
    const TidyAttrId TidyAttr_ACCEPT_CHARSET
    const TidyAttrId TidyAttr_ACCESSKEY
    const TidyAttrId TidyAttr_ACTION
    const TidyAttrId TidyAttr_ADD_DATE
    const TidyAttrId TidyAttr_ALIGN
    const TidyAttrId TidyAttr_ALINK
    const TidyAttrId TidyAttr_ALLOWFULLSCREEN
    const TidyAttrId TidyAttr_ALT
    const TidyAttrId TidyAttr_ARCHIVE
    const TidyAttrId TidyAttr_ARIA_ACTIVEDESCENDANT
    const TidyAttrId TidyAttr_ARIA_ATOMIC
    const TidyAttrId TidyAttr_ARIA_AUTOCOMPLETE
    const TidyAttrId TidyAttr_ARIA_BUSY
    const TidyAttrId TidyAttr_ARIA_CHECKED
    const TidyAttrId TidyAttr_ARIA_CONTROLS
    const TidyAttrId TidyAttr_ARIA_DESCRIBEDBY
    const TidyAttrId TidyAttr_ARIA_DISABLED
    const TidyAttrId TidyAttr_ARIA_DROPEFFECT
    const TidyAttrId TidyAttr_ARIA_EXPANDED
    const TidyAttrId TidyAttr_ARIA_FLOWTO
    const TidyAttrId TidyAttr_ARIA_GRABBED
    const TidyAttrId TidyAttr_ARIA_HASPOPUP
    const TidyAttrId TidyAttr_ARIA_HIDDEN
    const TidyAttrId TidyAttr_ARIA_INVALID
    const TidyAttrId TidyAttr_ARIA_LABEL
    const TidyAttrId TidyAttr_ARIA_LABELLEDBY
    const TidyAttrId TidyAttr_ARIA_LEVEL
    const TidyAttrId TidyAttr_ARIA_LIVE
    const TidyAttrId TidyAttr_ARIA_MULTILINE
    const TidyAttrId TidyAttr_ARIA_MULTISELECTABLE
    const TidyAttrId TidyAttr_ARIA_ORIENTATION
    const TidyAttrId TidyAttr_ARIA_OWNS
    const TidyAttrId TidyAttr_ARIA_POSINSET
    const TidyAttrId TidyAttr_ARIA_PRESSED
    const TidyAttrId TidyAttr_ARIA_READONLY
    const TidyAttrId TidyAttr_ARIA_RELEVANT
    const TidyAttrId TidyAttr_ARIA_REQUIRED
    const TidyAttrId TidyAttr_ARIA_SELECTED
    const TidyAttrId TidyAttr_ARIA_SETSIZE
    const TidyAttrId TidyAttr_ARIA_SORT
    const TidyAttrId TidyAttr_ARIA_VALUEMAX
    const TidyAttrId TidyAttr_ARIA_VALUEMIN
    const TidyAttrId TidyAttr_ARIA_VALUENOW
    const TidyAttrId TidyAttr_ARIA_VALUETEXT
    const TidyAttrId TidyAttr_AS
    const TidyAttrId TidyAttr_ASYNC
    const TidyAttrId TidyAttr_AUTOCOMPLETE
    const TidyAttrId TidyAttr_AUTOFOCUS
    const TidyAttrId TidyAttr_AUTOPLAY
    const TidyAttrId TidyAttr_AXIS
    const TidyAttrId TidyAttr_BACKGROUND
    const TidyAttrId TidyAttr_BASEPROFILE
    const TidyAttrId TidyAttr_BGCOLOR
    const TidyAttrId TidyAttr_BGPROPERTIES
    const TidyAttrId TidyAttr_BORDER
    const TidyAttrId TidyAttr_BORDERCOLOR
    const TidyAttrId TidyAttr_BOTTOMMARGIN
    const TidyAttrId TidyAttr_CELLPADDING
    const TidyAttrId TidyAttr_CELLSPACING
    const TidyAttrId TidyAttr_CHALLENGE
    const TidyAttrId TidyAttr_CHAR
    const TidyAttrId TidyAttr_CHAROFF
    const TidyAttrId TidyAttr_CHARSET
    const TidyAttrId TidyAttr_CHECKED
    const TidyAttrId TidyAttr_CITE
    const TidyAttrId TidyAttr_CLASS
    const TidyAttrId TidyAttr_CLASSID
    const TidyAttrId TidyAttr_CLEAR
    const TidyAttrId TidyAttr_CODE
    const TidyAttrId TidyAttr_CODEBASE
    const TidyAttrId TidyAttr_CODETYPE
    const TidyAttrId TidyAttr_COLOR
    const TidyAttrId TidyAttr_COLORINTERPOLATION
    const TidyAttrId TidyAttr_COLORRENDERING
    const TidyAttrId TidyAttr_COLS
    const TidyAttrId TidyAttr_COLSPAN
    const TidyAttrId TidyAttr_COMPACT
    const TidyAttrId TidyAttr_CONTENT
    const TidyAttrId TidyAttr_CONTENTEDITABLE
    const TidyAttrId TidyAttr_CONTENTSCRIPTTYPE
    const TidyAttrId TidyAttr_CONTENTSTYLETYPE
    const TidyAttrId TidyAttr_CONTEXTMENU
    const TidyAttrId TidyAttr_CONTROLS
    const TidyAttrId TidyAttr_COORDS
    const TidyAttrId TidyAttr_CROSSORIGIN
    const TidyAttrId TidyAttr_DATA
    const TidyAttrId TidyAttr_DATAFLD
    const TidyAttrId TidyAttr_DATAFORMATAS
    const TidyAttrId TidyAttr_DATAPAGESIZE
    const TidyAttrId TidyAttr_DATASRC
    const TidyAttrId TidyAttr_DATATYPE
    const TidyAttrId TidyAttr_DATETIME
    const TidyAttrId TidyAttr_DECLARE
    const TidyAttrId TidyAttr_DEFAULT
    const TidyAttrId TidyAttr_DEFER
    const TidyAttrId TidyAttr_DIR
    const TidyAttrId TidyAttr_DIRNAME
    const TidyAttrId TidyAttr_DISABLED
    const TidyAttrId TidyAttr_DISPLAY
    const TidyAttrId TidyAttr_DOWNLOAD
    const TidyAttrId TidyAttr_DRAGGABLE
    const TidyAttrId TidyAttr_DROPZONE
    const TidyAttrId TidyAttr_ENCODING
    const TidyAttrId TidyAttr_ENCTYPE
    const TidyAttrId TidyAttr_EVENT
    const TidyAttrId TidyAttr_FACE
    const TidyAttrId TidyAttr_FILL
    const TidyAttrId TidyAttr_FILLOPACITY
    const TidyAttrId TidyAttr_FILLRULE
    const TidyAttrId TidyAttr_FOR
    const TidyAttrId TidyAttr_FORM
    const TidyAttrId TidyAttr_FORMACTION
    const TidyAttrId TidyAttr_FORMENCTYPE
    const TidyAttrId TidyAttr_FORMMETHOD
    const TidyAttrId TidyAttr_FORMNOVALIDATE
    const TidyAttrId TidyAttr_FORMTARGET
    const TidyAttrId TidyAttr_FRAME
    const TidyAttrId TidyAttr_FRAMEBORDER
    const TidyAttrId TidyAttr_FRAMESPACING
    const TidyAttrId TidyAttr_GRIDX
    const TidyAttrId TidyAttr_GRIDY
    const TidyAttrId TidyAttr_HEADERS
    const TidyAttrId TidyAttr_HEIGHT
    const TidyAttrId TidyAttr_HIDDEN
    const TidyAttrId TidyAttr_HIGH
    const TidyAttrId TidyAttr_HREF
    const TidyAttrId TidyAttr_HREFLANG
    const TidyAttrId TidyAttr_HSPACE
    const TidyAttrId TidyAttr_HTTP_EQUIV
    const TidyAttrId TidyAttr_ICON
    const TidyAttrId TidyAttr_ID
    const TidyAttrId TidyAttr_INLIST
    const TidyAttrId TidyAttr_INTEGRITY
    const TidyAttrId TidyAttr_IS
    const TidyAttrId TidyAttr_ISMAP
    const TidyAttrId TidyAttr_ITEMID
    const TidyAttrId TidyAttr_ITEMPROP
    const TidyAttrId TidyAttr_ITEMREF
    const TidyAttrId TidyAttr_ITEMSCOPE
    const TidyAttrId TidyAttr_ITEMTYPE
    const TidyAttrId TidyAttr_KEYTYPE
    const TidyAttrId TidyAttr_KIND
    const TidyAttrId TidyAttr_LABEL
    const TidyAttrId TidyAttr_LANG
    const TidyAttrId TidyAttr_LANGUAGE
    const TidyAttrId TidyAttr_LAST_MODIFIED
    const TidyAttrId TidyAttr_LAST_VISIT
    const TidyAttrId TidyAttr_LEFTMARGIN
    const TidyAttrId TidyAttr_LINK
    const TidyAttrId TidyAttr_LIST
    const TidyAttrId TidyAttr_LOADING
    const TidyAttrId TidyAttr_LONGDESC
    const TidyAttrId TidyAttr_LOOP
    const TidyAttrId TidyAttr_LOW
    const TidyAttrId TidyAttr_LOWSRC
    const TidyAttrId TidyAttr_MANIFEST
    const TidyAttrId TidyAttr_MARGINHEIGHT
    const TidyAttrId TidyAttr_MARGINWIDTH
    const TidyAttrId TidyAttr_MAX
    const TidyAttrId TidyAttr_MAXLENGTH
    const TidyAttrId TidyAttr_MEDIA
    const TidyAttrId TidyAttr_MEDIAGROUP
    const TidyAttrId TidyAttr_METHOD
    const TidyAttrId TidyAttr_METHODS
    const TidyAttrId TidyAttr_MIN
    const TidyAttrId TidyAttr_MULTIPLE
    const TidyAttrId TidyAttr_MUTED
    const TidyAttrId TidyAttr_N
    const TidyAttrId TidyAttr_NAME
    const TidyAttrId TidyAttr_NOHREF
    const TidyAttrId TidyAttr_NORESIZE
    const TidyAttrId TidyAttr_NOSHADE
    const TidyAttrId TidyAttr_NOVALIDATE
    const TidyAttrId TidyAttr_NOWRAP
    const TidyAttrId TidyAttr_OBJECT
    const TidyAttrId TidyAttr_OPACITY
    const TidyAttrId TidyAttr_OPEN
    const TidyAttrId TidyAttr_OPTIMUM
    const TidyAttrId TidyAttr_OnABORT
    const TidyAttrId TidyAttr_OnAFTERPRINT
    const TidyAttrId TidyAttr_OnAFTERUPDATE
    const TidyAttrId TidyAttr_OnBEFOREPRINT
    const TidyAttrId TidyAttr_OnBEFOREUNLOAD
    const TidyAttrId TidyAttr_OnBEFOREUPDATE
    const TidyAttrId TidyAttr_OnBLUR
    const TidyAttrId TidyAttr_OnCANPLAY
    const TidyAttrId TidyAttr_OnCANPLAYTHROUGH
    const TidyAttrId TidyAttr_OnCHANGE
    const TidyAttrId TidyAttr_OnCLICK
    const TidyAttrId TidyAttr_OnCONTEXTMENU
    const TidyAttrId TidyAttr_OnCUECHANGE
    const TidyAttrId TidyAttr_OnDATAAVAILABLE
    const TidyAttrId TidyAttr_OnDATASETCHANGED
    const TidyAttrId TidyAttr_OnDATASETCOMPLETE
    const TidyAttrId TidyAttr_OnDBLCLICK
    const TidyAttrId TidyAttr_OnDRAG
    const TidyAttrId TidyAttr_OnDRAGEND
    const TidyAttrId TidyAttr_OnDRAGENTER
    const TidyAttrId TidyAttr_OnDRAGLEAVE
    const TidyAttrId TidyAttr_OnDRAGOVER
    const TidyAttrId TidyAttr_OnDRAGSTART
    const TidyAttrId TidyAttr_OnDROP
    const TidyAttrId TidyAttr_OnDURATIONCHANGE
    const TidyAttrId TidyAttr_OnEMPTIED
    const TidyAttrId TidyAttr_OnENDED
    const TidyAttrId TidyAttr_OnERROR
    const TidyAttrId TidyAttr_OnERRORUPDATE
    const TidyAttrId TidyAttr_OnFOCUS
    const TidyAttrId TidyAttr_OnHASHCHANGE
    const TidyAttrId TidyAttr_OnINPUT
    const TidyAttrId TidyAttr_OnINVALID
    const TidyAttrId TidyAttr_OnKEYDOWN
    const TidyAttrId TidyAttr_OnKEYPRESS
    const TidyAttrId TidyAttr_OnKEYUP
    const TidyAttrId TidyAttr_OnLOAD
    const TidyAttrId TidyAttr_OnLOADEDDATA
    const TidyAttrId TidyAttr_OnLOADEDMETADATA
    const TidyAttrId TidyAttr_OnLOADSTART
    const TidyAttrId TidyAttr_OnMESSAGE
    const TidyAttrId TidyAttr_OnMOUSEDOWN
    const TidyAttrId TidyAttr_OnMOUSEMOVE
    const TidyAttrId TidyAttr_OnMOUSEOUT
    const TidyAttrId TidyAttr_OnMOUSEOVER
    const TidyAttrId TidyAttr_OnMOUSEUP
    const TidyAttrId TidyAttr_OnMOUSEWHEEL
    const TidyAttrId TidyAttr_OnOFFLINE
    const TidyAttrId TidyAttr_OnONLINE
    const TidyAttrId TidyAttr_OnPAGEHIDE
    const TidyAttrId TidyAttr_OnPAGESHOW
    const TidyAttrId TidyAttr_OnPAUSE
    const TidyAttrId TidyAttr_OnPLAY
    const TidyAttrId TidyAttr_OnPLAYING
    const TidyAttrId TidyAttr_OnPOPSTATE
    const TidyAttrId TidyAttr_OnPROGRESS
    const TidyAttrId TidyAttr_OnRATECHANGE
    const TidyAttrId TidyAttr_OnREADYSTATECHANGE
    const TidyAttrId TidyAttr_OnREDO
    const TidyAttrId TidyAttr_OnRESET
    const TidyAttrId TidyAttr_OnRESIZE
    const TidyAttrId TidyAttr_OnROWENTER
    const TidyAttrId TidyAttr_OnROWEXIT
    const TidyAttrId TidyAttr_OnSCROLL
    const TidyAttrId TidyAttr_OnSEEKED
    const TidyAttrId TidyAttr_OnSEEKING
    const TidyAttrId TidyAttr_OnSELECT
    const TidyAttrId TidyAttr_OnSHOW
    const TidyAttrId TidyAttr_OnSTALLED
    const TidyAttrId TidyAttr_OnSTORAGE
    const TidyAttrId TidyAttr_OnSUBMIT
    const TidyAttrId TidyAttr_OnSUSPEND
    const TidyAttrId TidyAttr_OnTIMEUPDATE
    const TidyAttrId TidyAttr_OnUNDO
    const TidyAttrId TidyAttr_OnUNLOAD
    const TidyAttrId TidyAttr_OnVOLUMECHANGE
    const TidyAttrId TidyAttr_OnWAITING
    const TidyAttrId TidyAttr_PATTERN
    const TidyAttrId TidyAttr_PLACEHOLDER
    const TidyAttrId TidyAttr_PLAYSINLINE
    const TidyAttrId TidyAttr_POSTER
    const TidyAttrId TidyAttr_PREFIX
    const TidyAttrId TidyAttr_PRELOAD
    const TidyAttrId TidyAttr_PRESERVEASPECTRATIO
    const TidyAttrId TidyAttr_PROFILE
    const TidyAttrId TidyAttr_PROMPT
    const TidyAttrId TidyAttr_PROPERTY
    const TidyAttrId TidyAttr_PUBDATE
    const TidyAttrId TidyAttr_RADIOGROUP
    const TidyAttrId TidyAttr_RBSPAN
    const TidyAttrId TidyAttr_READONLY
    const TidyAttrId TidyAttr_REL
    const TidyAttrId TidyAttr_REQUIRED
    const TidyAttrId TidyAttr_RESOURCE
    const TidyAttrId TidyAttr_REV
    const TidyAttrId TidyAttr_REVERSED
    const TidyAttrId TidyAttr_RIGHTMARGIN
    const TidyAttrId TidyAttr_ROLE
    const TidyAttrId TidyAttr_ROWS
    const TidyAttrId TidyAttr_ROWSPAN
    const TidyAttrId TidyAttr_RULES
    const TidyAttrId TidyAttr_SANDBOX
    const TidyAttrId TidyAttr_SCHEME
    const TidyAttrId TidyAttr_SCOPE
    const TidyAttrId TidyAttr_SCOPED
    const TidyAttrId TidyAttr_SCROLLING
    const TidyAttrId TidyAttr_SDAFORM
    const TidyAttrId TidyAttr_SDAPREF
    const TidyAttrId TidyAttr_SDASUFF
    const TidyAttrId TidyAttr_SEAMLESS
    const TidyAttrId TidyAttr_SELECTED
    const TidyAttrId TidyAttr_SHAPE
    const TidyAttrId TidyAttr_SHOWGRID
    const TidyAttrId TidyAttr_SHOWGRIDX
    const TidyAttrId TidyAttr_SHOWGRIDY
    const TidyAttrId TidyAttr_SIZE
    const TidyAttrId TidyAttr_SIZES
    const TidyAttrId TidyAttr_SLOT
    const TidyAttrId TidyAttr_SPAN
    const TidyAttrId TidyAttr_SPELLCHECK
    const TidyAttrId TidyAttr_SRC
    const TidyAttrId TidyAttr_SRCDOC
    const TidyAttrId TidyAttr_SRCLANG
    const TidyAttrId TidyAttr_SRCSET
    const TidyAttrId TidyAttr_STANDBY
    const TidyAttrId TidyAttr_START
    const TidyAttrId TidyAttr_STEP
    const TidyAttrId TidyAttr_STROKE
    const TidyAttrId TidyAttr_STROKEDASHARRAY
    const TidyAttrId TidyAttr_STROKEDASHOFFSET
    const TidyAttrId TidyAttr_STROKELINECAP
    const TidyAttrId TidyAttr_STROKELINEJOIN
    const TidyAttrId TidyAttr_STROKEMITERLIMIT
    const TidyAttrId TidyAttr_STROKEOPACITY
    const TidyAttrId TidyAttr_STROKEWIDTH
    const TidyAttrId TidyAttr_STYLE
    const TidyAttrId TidyAttr_SUMMARY
    const TidyAttrId TidyAttr_TABINDEX
    const TidyAttrId TidyAttr_TARGET
    const TidyAttrId TidyAttr_TEXT
    const TidyAttrId TidyAttr_TITLE
    const TidyAttrId TidyAttr_TOPMARGIN
    const TidyAttrId TidyAttr_TRANSLATE
    const TidyAttrId TidyAttr_TYPE
    const TidyAttrId TidyAttr_TYPEOF
    const TidyAttrId TidyAttr_UNKNOWN
    const TidyAttrId TidyAttr_URN
    const TidyAttrId TidyAttr_USEMAP
    const TidyAttrId TidyAttr_VALIGN
    const TidyAttrId TidyAttr_VALUE
    const TidyAttrId TidyAttr_VALUETYPE
    const TidyAttrId TidyAttr_VERSION
    const TidyAttrId TidyAttr_VIEWBOX
    const TidyAttrId TidyAttr_VLINK
    const TidyAttrId TidyAttr_VOCAB
    const TidyAttrId TidyAttr_VSPACE
    const TidyAttrId TidyAttr_WIDTH
    const TidyAttrId TidyAttr_WRAP
    const TidyAttrId TidyAttr_X
    const TidyAttrId TidyAttr_XMLNS
    const TidyAttrId TidyAttr_XMLNSXLINK
    const TidyAttrId TidyAttr_XML_LANG
    const TidyAttrId TidyAttr_XML_SPACE
    const TidyAttrId TidyAttr_Y
    const TidyAttrId TidyAttr_ZOOMANDPAN

    const TidyAttrSortStrategy TidySortAttrAlpha
    const TidyAttrSortStrategy TidySortAttrNone

    const TidyConfigCategory TidyDiagnostics
    const TidyConfigCategory TidyDisplay
    const TidyConfigCategory TidyDocumentIO
    const TidyConfigCategory TidyEncoding
    const TidyConfigCategory TidyFileIO
    const TidyConfigCategory TidyInternalCategory
    const TidyConfigCategory TidyMarkupCleanup
    const TidyConfigCategory TidyMarkupEntities
    const TidyConfigCategory TidyMarkupRepair
    const TidyConfigCategory TidyMarkupTeach
    const TidyConfigCategory TidyMarkupXForm
    const TidyConfigCategory TidyPrettyPrint
    const TidyConfigCategory TidyUnknownCategory

    const TidyDoctypeModes TidyDoctypeAuto
    const TidyDoctypeModes TidyDoctypeHtml5
    const TidyDoctypeModes TidyDoctypeLoose
    const TidyDoctypeModes TidyDoctypeOmit
    const TidyDoctypeModes TidyDoctypeStrict
    const TidyDoctypeModes TidyDoctypeUser

    const TidyDupAttrModes TidyKeepFirst
    const TidyDupAttrModes TidyKeepLast

    const TidyEncodingOptions TidyEncAscii
    const TidyEncodingOptions TidyEncBig5
    const TidyEncodingOptions TidyEncIbm858
    const TidyEncodingOptions TidyEncIso2022
    const TidyEncodingOptions TidyEncLatin0
    const TidyEncodingOptions TidyEncLatin1
    const TidyEncodingOptions TidyEncMac
    const TidyEncodingOptions TidyEncRaw
    const TidyEncodingOptions TidyEncShiftjis
    const TidyEncodingOptions TidyEncUtf16
    const TidyEncodingOptions TidyEncUtf16be
    const TidyEncodingOptions TidyEncUtf16le
    const TidyEncodingOptions TidyEncUtf8
    const TidyEncodingOptions TidyEncWin1252

    const TidyFormatParameterType tidyFormatType_DOUBLE
    const TidyFormatParameterType tidyFormatType_INT
    const TidyFormatParameterType tidyFormatType_STRING
    const TidyFormatParameterType tidyFormatType_UINT
    const TidyFormatParameterType tidyFormatType_UNKNOWN

    const TidyLineEnding TidyCR
    const TidyLineEnding TidyCRLF
    const TidyLineEnding TidyLF

    const TidyNodeType TidyNode_Asp
    const TidyNodeType TidyNode_CDATA
    const TidyNodeType TidyNode_Comment
    const TidyNodeType TidyNode_DocType
    const TidyNodeType TidyNode_End
    const TidyNodeType TidyNode_Jste
    const TidyNodeType TidyNode_Php
    const TidyNodeType TidyNode_ProcIns
    const TidyNodeType TidyNode_Root
    const TidyNodeType TidyNode_Section
    const TidyNodeType TidyNode_Start
    const TidyNodeType TidyNode_StartEnd
    const TidyNodeType TidyNode_Text
    const TidyNodeType TidyNode_XmlDecl

    const TidyOptionId N_TIDY_OPTIONS
    const TidyOptionId TidyAccessibilityCheckLevel
    const TidyOptionId TidyAltText
    const TidyOptionId TidyAnchorAsName
    const TidyOptionId TidyAsciiChars
    const TidyOptionId TidyBlockTags
    const TidyOptionId TidyBodyOnly
    const TidyOptionId TidyBreakBeforeBR
    const TidyOptionId TidyCSSPrefix
    const TidyOptionId TidyCharEncoding
    const TidyOptionId TidyCoerceEndTags
    const TidyOptionId TidyCustomTags
    const TidyOptionId TidyDecorateInferredUL
    const TidyOptionId TidyDoctype
    const TidyOptionId TidyDoctypeMode
    const TidyOptionId TidyDropEmptyElems
    const TidyOptionId TidyDropEmptyParas
    const TidyOptionId TidyDropPropAttrs
    const TidyOptionId TidyDuplicateAttrs
    const TidyOptionId TidyEmacs
    const TidyOptionId TidyEmacsFile
    const TidyOptionId TidyEmptyTags
    const TidyOptionId TidyEncloseBlockText
    const TidyOptionId TidyEncloseBodyText
    const TidyOptionId TidyErrFile
    const TidyOptionId TidyEscapeCdata
    const TidyOptionId TidyEscapeScripts
    const TidyOptionId TidyFixBackslash
    const TidyOptionId TidyFixComments
    const TidyOptionId TidyFixUri
    const TidyOptionId TidyForceOutput
    const TidyOptionId TidyGDocClean
    const TidyOptionId TidyHideComments
    const TidyOptionId TidyHtmlOut
    const TidyOptionId TidyInCharEncoding
    const TidyOptionId TidyIndentAttributes
    const TidyOptionId TidyIndentCdata
    const TidyOptionId TidyIndentContent
    const TidyOptionId TidyIndentSpaces
    const TidyOptionId TidyInlineTags
    const TidyOptionId TidyJoinClasses
    const TidyOptionId TidyJoinStyles
    const TidyOptionId TidyKeepFileTimes
    const TidyOptionId TidyKeepTabs
    const TidyOptionId TidyLiteralAttribs
    const TidyOptionId TidyLogicalEmphasis
    const TidyOptionId TidyLowerLiterals
    const TidyOptionId TidyMakeBare
    const TidyOptionId TidyMakeClean
    const TidyOptionId TidyMark
    const TidyOptionId TidyMergeDivs
    const TidyOptionId TidyMergeEmphasis
    const TidyOptionId TidyMergeSpans
    const TidyOptionId TidyMetaCharset
    const TidyOptionId TidyMuteReports
    const TidyOptionId TidyMuteShow
    const TidyOptionId TidyNCR
    const TidyOptionId TidyNewline
    const TidyOptionId TidyNumEntities
    const TidyOptionId TidyOmitOptionalTags
    const TidyOptionId TidyOutCharEncoding
    const TidyOptionId TidyOutFile
    const TidyOptionId TidyOutputBOM
    const TidyOptionId TidyPPrintTabs
    const TidyOptionId TidyPreTags
    const TidyOptionId TidyPreserveEntities
    const TidyOptionId TidyPriorityAttributes
    const TidyOptionId TidyPunctWrap
    const TidyOptionId TidyQuiet
    const TidyOptionId TidyQuoteAmpersand
    const TidyOptionId TidyQuoteMarks
    const TidyOptionId TidyQuoteNbsp
    const TidyOptionId TidyReplaceColor
    const TidyOptionId TidyShowErrors
    const TidyOptionId TidyShowFilename
    const TidyOptionId TidyShowInfo
    const TidyOptionId TidyShowMarkup
    const TidyOptionId TidyShowMetaChange
    const TidyOptionId TidyShowWarnings
    const TidyOptionId TidySkipNested
    const TidyOptionId TidySortAttributes
    const TidyOptionId TidyStrictTagsAttr
    const TidyOptionId TidyStyleTags
    const TidyOptionId TidyTabSize
    const TidyOptionId TidyUnknownOption
    const TidyOptionId TidyUpperCaseAttrs
    const TidyOptionId TidyUpperCaseTags
    const TidyOptionId TidyUseCustomTags
    const TidyOptionId TidyVertSpace
    const TidyOptionId TidyWarnPropAttrs
    const TidyOptionId TidyWord2000
    const TidyOptionId TidyWrapAsp
    const TidyOptionId TidyWrapAttVals
    const TidyOptionId TidyWrapJste
    const TidyOptionId TidyWrapLen
    const TidyOptionId TidyWrapPhp
    const TidyOptionId TidyWrapScriptlets
    const TidyOptionId TidyWrapSection
    const TidyOptionId TidyWriteBack
    const TidyOptionId TidyXhtmlOut
    const TidyOptionId TidyXmlDecl
    const TidyOptionId TidyXmlOut
    const TidyOptionId TidyXmlPIs
    const TidyOptionId TidyXmlSpace
    const TidyOptionId TidyXmlTags

    const TidyOptionType TidyBoolean
    const TidyOptionType TidyInteger
    const TidyOptionType TidyString

    const TidyReportLevel TidyAccess
    const TidyReportLevel TidyBadDocument
    const TidyReportLevel TidyConfig
    const TidyReportLevel TidyDialogueDoc
    const TidyReportLevel TidyDialogueFootnote
    const TidyReportLevel TidyDialogueInfo
    const TidyReportLevel TidyDialogueSummary
    const TidyReportLevel TidyError
    const TidyReportLevel TidyFatal
    const TidyReportLevel TidyInfo
    const TidyReportLevel TidyWarning

    const TidyTagId N_TIDY_TAGS
    const TidyTagId TidyTag_A
    const TidyTagId TidyTag_ABBR
    const TidyTagId TidyTag_ACRONYM
    const TidyTagId TidyTag_ADDRESS
    const TidyTagId TidyTag_ALIGN
    const TidyTagId TidyTag_APPLET
    const TidyTagId TidyTag_AREA
    const TidyTagId TidyTag_ARTICLE
    const TidyTagId TidyTag_ASIDE
    const TidyTagId TidyTag_AUDIO
    const TidyTagId TidyTag_B
    const TidyTagId TidyTag_BASE
    const TidyTagId TidyTag_BASEFONT
    const TidyTagId TidyTag_BDI
    const TidyTagId TidyTag_BDO
    const TidyTagId TidyTag_BGSOUND
    const TidyTagId TidyTag_BIG
    const TidyTagId TidyTag_BLINK
    const TidyTagId TidyTag_BLOCKQUOTE
    const TidyTagId TidyTag_BODY
    const TidyTagId TidyTag_BR
    const TidyTagId TidyTag_BUTTON
    const TidyTagId TidyTag_CANVAS
    const TidyTagId TidyTag_CAPTION
    const TidyTagId TidyTag_CENTER
    const TidyTagId TidyTag_CITE
    const TidyTagId TidyTag_CODE
    const TidyTagId TidyTag_COL
    const TidyTagId TidyTag_COLGROUP
    const TidyTagId TidyTag_COMMAND
    const TidyTagId TidyTag_COMMENT
    const TidyTagId TidyTag_DATA
    const TidyTagId TidyTag_DATALIST
    const TidyTagId TidyTag_DD
    const TidyTagId TidyTag_DEL
    const TidyTagId TidyTag_DETAILS
    const TidyTagId TidyTag_DFN
    const TidyTagId TidyTag_DIALOG
    const TidyTagId TidyTag_DIR
    const TidyTagId TidyTag_DIV
    const TidyTagId TidyTag_DL
    const TidyTagId TidyTag_DT
    const TidyTagId TidyTag_EM
    const TidyTagId TidyTag_EMBED
    const TidyTagId TidyTag_FIELDSET
    const TidyTagId TidyTag_FIGCAPTION
    const TidyTagId TidyTag_FIGURE
    const TidyTagId TidyTag_FONT
    const TidyTagId TidyTag_FOOTER
    const TidyTagId TidyTag_FORM
    const TidyTagId TidyTag_FRAME
    const TidyTagId TidyTag_FRAMESET
    const TidyTagId TidyTag_H1
    const TidyTagId TidyTag_H2
    const TidyTagId TidyTag_H3
    const TidyTagId TidyTag_H4
    const TidyTagId TidyTag_H5
    const TidyTagId TidyTag_H6
    const TidyTagId TidyTag_HEAD
    const TidyTagId TidyTag_HEADER
    const TidyTagId TidyTag_HGROUP
    const TidyTagId TidyTag_HR
    const TidyTagId TidyTag_HTML
    const TidyTagId TidyTag_I
    const TidyTagId TidyTag_IFRAME
    const TidyTagId TidyTag_ILAYER
    const TidyTagId TidyTag_IMG
    const TidyTagId TidyTag_INPUT
    const TidyTagId TidyTag_INS
    const TidyTagId TidyTag_ISINDEX
    const TidyTagId TidyTag_KBD
    const TidyTagId TidyTag_KEYGEN
    const TidyTagId TidyTag_LABEL
    const TidyTagId TidyTag_LAYER
    const TidyTagId TidyTag_LEGEND
    const TidyTagId TidyTag_LI
    const TidyTagId TidyTag_LINK
    const TidyTagId TidyTag_LISTING
    const TidyTagId TidyTag_MAIN
    const TidyTagId TidyTag_MAP
    const TidyTagId TidyTag_MARK
    const TidyTagId TidyTag_MARQUEE
    const TidyTagId TidyTag_MATHML
    const TidyTagId TidyTag_MENU
    const TidyTagId TidyTag_MENUITEM
    const TidyTagId TidyTag_META
    const TidyTagId TidyTag_METER
    const TidyTagId TidyTag_MULTICOL
    const TidyTagId TidyTag_NAV
    const TidyTagId TidyTag_NEXTID
    const TidyTagId TidyTag_NOBR
    const TidyTagId TidyTag_NOEMBED
    const TidyTagId TidyTag_NOFRAMES
    const TidyTagId TidyTag_NOLAYER
    const TidyTagId TidyTag_NOSAVE
    const TidyTagId TidyTag_NOSCRIPT
    const TidyTagId TidyTag_OBJECT
    const TidyTagId TidyTag_OL
    const TidyTagId TidyTag_OPTGROUP
    const TidyTagId TidyTag_OPTION
    const TidyTagId TidyTag_OUTPUT
    const TidyTagId TidyTag_P
    const TidyTagId TidyTag_PARAM
    const TidyTagId TidyTag_PICTURE
    const TidyTagId TidyTag_PLAINTEXT
    const TidyTagId TidyTag_PRE
    const TidyTagId TidyTag_PROGRESS
    const TidyTagId TidyTag_Q
    const TidyTagId TidyTag_RB
    const TidyTagId TidyTag_RBC
    const TidyTagId TidyTag_RP
    const TidyTagId TidyTag_RT
    const TidyTagId TidyTag_RTC
    const TidyTagId TidyTag_RUBY
    const TidyTagId TidyTag_S
    const TidyTagId TidyTag_SAMP
    const TidyTagId TidyTag_SCRIPT
    const TidyTagId TidyTag_SECTION
    const TidyTagId TidyTag_SELECT
    const TidyTagId TidyTag_SERVER
    const TidyTagId TidyTag_SERVLET
    const TidyTagId TidyTag_SLOT
    const TidyTagId TidyTag_SMALL
    const TidyTagId TidyTag_SOURCE
    const TidyTagId TidyTag_SPACER
    const TidyTagId TidyTag_SPAN
    const TidyTagId TidyTag_STRIKE
    const TidyTagId TidyTag_STRONG
    const TidyTagId TidyTag_STYLE
    const TidyTagId TidyTag_SUB
    const TidyTagId TidyTag_SUMMARY
    const TidyTagId TidyTag_SUP
    const TidyTagId TidyTag_SVG
    const TidyTagId TidyTag_TABLE
    const TidyTagId TidyTag_TBODY
    const TidyTagId TidyTag_TD
    const TidyTagId TidyTag_TEMPLATE
    const TidyTagId TidyTag_TEXTAREA
    const TidyTagId TidyTag_TFOOT
    const TidyTagId TidyTag_TH
    const TidyTagId TidyTag_THEAD
    const TidyTagId TidyTag_TIME
    const TidyTagId TidyTag_TITLE
    const TidyTagId TidyTag_TR
    const TidyTagId TidyTag_TRACK
    const TidyTagId TidyTag_TT
    const TidyTagId TidyTag_U
    const TidyTagId TidyTag_UL
    const TidyTagId TidyTag_UNKNOWN
    const TidyTagId TidyTag_VAR
    const TidyTagId TidyTag_VIDEO
    const TidyTagId TidyTag_WBR
    const TidyTagId TidyTag_XMP

    const TidyTriState TidyAutoState
    const TidyTriState TidyNoState
    const TidyTriState TidyYesState

    const TidyUppercase TidyUppercaseNo
    const TidyUppercase TidyUppercasePreserve
    const TidyUppercase TidyUppercaseYes

    const TidyUseCustomTagsState TidyCustomBlocklevel
    const TidyUseCustomTagsState TidyCustomEmpty
    const TidyUseCustomTagsState TidyCustomInline
    const TidyUseCustomTagsState TidyCustomNo
    const TidyUseCustomTagsState TidyCustomPre

    const tidyStrings ADDED_MISSING_CHARSET
    const tidyStrings ANCHOR_DUPLICATED
    const tidyStrings ANCHOR_NOT_UNIQUE
    const tidyStrings APOS_UNDEFINED
    const tidyStrings APPLET_MISSING_ALT
    const tidyStrings AREA_MISSING_ALT
    const tidyStrings ASCII_REQUIRES_DESCRIPTION
    const tidyStrings ASSOCIATE_LABELS_EXPLICITLY
    const tidyStrings ASSOCIATE_LABELS_EXPLICITLY_FOR
    const tidyStrings ASSOCIATE_LABELS_EXPLICITLY_ID
    const tidyStrings ATTRIBUTE_IS_NOT_ALLOWED
    const tidyStrings ATTRIBUTE_VALUE_REPLACED
    const tidyStrings ATTR_VALUE_NOT_LCASE
    const tidyStrings AUDIO_MISSING_TEXT_AIFF
    const tidyStrings AUDIO_MISSING_TEXT_AU
    const tidyStrings AUDIO_MISSING_TEXT_RA
    const tidyStrings AUDIO_MISSING_TEXT_RM
    const tidyStrings AUDIO_MISSING_TEXT_SND
    const tidyStrings AUDIO_MISSING_TEXT_WAV
    const tidyStrings BACKSLASH_IN_URI
    const tidyStrings BAD_ATTRIBUTE_VALUE
    const tidyStrings BAD_ATTRIBUTE_VALUE_REPLACED
    const tidyStrings BAD_CDATA_CONTENT
    const tidyStrings BAD_SUMMARY_HTML5
    const tidyStrings BAD_SURROGATE_LEAD
    const tidyStrings BAD_SURROGATE_PAIR
    const tidyStrings BAD_SURROGATE_TAIL
    const tidyStrings BLANK_TITLE_ELEMENT
    const tidyStrings CANT_BE_NESTED
    const tidyStrings COERCE_TO_ENDTAG
    const tidyStrings COLOR_CONTRAST_ACTIVE_LINK
    const tidyStrings COLOR_CONTRAST_LINK
    const tidyStrings COLOR_CONTRAST_TEXT
    const tidyStrings COLOR_CONTRAST_VISITED_LINK
    const tidyStrings CONTENT_AFTER_BODY
    const tidyStrings CUSTOM_TAG_DETECTED
    const tidyStrings DATA_TABLE_MISSING_HEADERS
    const tidyStrings DATA_TABLE_MISSING_HEADERS_COLUMN
    const tidyStrings DATA_TABLE_MISSING_HEADERS_ROW
    const tidyStrings DATA_TABLE_REQUIRE_MARKUP_COLUMN_HEADERS
    const tidyStrings DATA_TABLE_REQUIRE_MARKUP_ROW_HEADERS
    const tidyStrings DISCARDING_UNEXPECTED
    const tidyStrings DOCTYPE_AFTER_TAGS
    const tidyStrings DOCTYPE_MISSING
    const tidyStrings DUPLICATE_FRAMESET
    const tidyStrings ELEMENT_NOT_EMPTY
    const tidyStrings ELEMENT_VERS_MISMATCH_ERROR
    const tidyStrings ELEMENT_VERS_MISMATCH_WARN
    const tidyStrings ENCODING_MISMATCH
    const tidyStrings ENSURE_PROGRAMMATIC_OBJECTS_ACCESSIBLE_APPLET
    const tidyStrings ENSURE_PROGRAMMATIC_OBJECTS_ACCESSIBLE_EMBED
    const tidyStrings ENSURE_PROGRAMMATIC_OBJECTS_ACCESSIBLE_OBJECT
    const tidyStrings ENSURE_PROGRAMMATIC_OBJECTS_ACCESSIBLE_SCRIPT
    const tidyStrings ESCAPED_ILLEGAL_URI
    const tidyStrings FILE_CANT_OPEN
    const tidyStrings FILE_CANT_OPEN_CFG
    const tidyStrings FILE_NOT_FILE
    const tidyStrings FIXED_BACKSLASH
    const tidyStrings FN_LINE_COLUMN_STRING
    const tidyStrings FOOTNOTE_TRIM_EMPTY_ELEMENT
    const tidyStrings FOUND_STYLE_IN_BODY
    const tidyStrings FRAME_MISSING_LONGDESC
    const tidyStrings FRAME_MISSING_NOFRAMES
    const tidyStrings FRAME_MISSING_TITLE
    const tidyStrings FRAME_SRC_INVALID
    const tidyStrings FRAME_TITLE_INVALID_NULL
    const tidyStrings FRAME_TITLE_INVALID_SPACES
    const tidyStrings HEADERS_IMPROPERLY_NESTED
    const tidyStrings HEADER_USED_FORMAT_TEXT
    const tidyStrings ID_NAME_MISMATCH
    const tidyStrings ILLEGAL_NESTING
    const tidyStrings ILLEGAL_URI_CODEPOINT
    const tidyStrings ILLEGAL_URI_REFERENCE
    const tidyStrings IMAGE_MAP_SERVER_SIDE_REQUIRES_CONVERSION
    const tidyStrings IMG_ALT_SUSPICIOUS_FILENAME
    const tidyStrings IMG_ALT_SUSPICIOUS_FILE_SIZE
    const tidyStrings IMG_ALT_SUSPICIOUS_PLACEHOLDER
    const tidyStrings IMG_ALT_SUSPICIOUS_TOO_LONG
    const tidyStrings IMG_BUTTON_MISSING_ALT
    const tidyStrings IMG_MAP_CLIENT_MISSING_TEXT_LINKS
    const tidyStrings IMG_MAP_SERVER_REQUIRES_TEXT_LINKS
    const tidyStrings IMG_MISSING_ALT
    const tidyStrings IMG_MISSING_DLINK
    const tidyStrings IMG_MISSING_LONGDESC
    const tidyStrings IMG_MISSING_LONGDESC_DLINK
    const tidyStrings INFORMATION_NOT_CONVEYED_APPLET
    const tidyStrings INFORMATION_NOT_CONVEYED_IMAGE
    const tidyStrings INFORMATION_NOT_CONVEYED_INPUT
    const tidyStrings INFORMATION_NOT_CONVEYED_OBJECT
    const tidyStrings INFORMATION_NOT_CONVEYED_SCRIPT
    const tidyStrings INSERTING_AUTO_ATTRIBUTE
    const tidyStrings INSERTING_TAG
    const tidyStrings INVALID_ATTRIBUTE
    const tidyStrings INVALID_NCR
    const tidyStrings INVALID_SGML_CHARS
    const tidyStrings INVALID_UTF16
    const tidyStrings INVALID_UTF8
    const tidyStrings INVALID_XML_ID
    const tidyStrings JOINING_ATTRIBUTE
    const tidyStrings LANGUAGE_INVALID
    const tidyStrings LANGUAGE_NOT_IDENTIFIED
    const tidyStrings LAYOUT_TABLES_LINEARIZE_PROPERLY
    const tidyStrings LAYOUT_TABLE_INVALID_MARKUP
    const tidyStrings LINE_COLUMN_STRING
    const tidyStrings LINK_TEXT_MISSING
    const tidyStrings LINK_TEXT_NOT_MEANINGFUL
    const tidyStrings LINK_TEXT_NOT_MEANINGFUL_CLICK_HERE
    const tidyStrings LINK_TEXT_TOO_LONG
    const tidyStrings LIST_USAGE_INVALID_LI
    const tidyStrings LIST_USAGE_INVALID_OL
    const tidyStrings LIST_USAGE_INVALID_UL
    const tidyStrings MALFORMED_COMMENT
    const tidyStrings MALFORMED_COMMENT_DROPPING
    const tidyStrings MALFORMED_COMMENT_EOS
    const tidyStrings MALFORMED_COMMENT_WARN
    const tidyStrings MALFORMED_DOCTYPE
    const tidyStrings METADATA_MISSING
    const tidyStrings METADATA_MISSING_REDIRECT_AUTOREFRESH
    const tidyStrings MISMATCHED_ATTRIBUTE_ERROR
    const tidyStrings MISMATCHED_ATTRIBUTE_WARN
    const tidyStrings MISSING_ATTRIBUTE
    const tidyStrings MISSING_ATTR_VALUE
    const tidyStrings MISSING_DOCTYPE
    const tidyStrings MISSING_ENDTAG_BEFORE
    const tidyStrings MISSING_ENDTAG_FOR
    const tidyStrings MISSING_ENDTAG_OPTIONAL
    const tidyStrings MISSING_IMAGEMAP
    const tidyStrings MISSING_QUOTEMARK
    const tidyStrings MISSING_QUOTEMARK_OPEN
    const tidyStrings MISSING_SEMICOLON
    const tidyStrings MISSING_SEMICOLON_NCR
    const tidyStrings MISSING_STARTTAG
    const tidyStrings MISSING_TITLE_ELEMENT
    const tidyStrings MOVED_STYLE_TO_HEAD
    const tidyStrings MULTIMEDIA_REQUIRES_TEXT
    const tidyStrings NESTED_EMPHASIS
    const tidyStrings NESTED_QUOTATION
    const tidyStrings NEWLINE_IN_URI
    const tidyStrings NEW_WINDOWS_REQUIRE_WARNING_BLANK
    const tidyStrings NEW_WINDOWS_REQUIRE_WARNING_NEW
    const tidyStrings NOFRAMES_CONTENT
    const tidyStrings NOFRAMES_INVALID_CONTENT
    const tidyStrings NOFRAMES_INVALID_LINK
    const tidyStrings NOFRAMES_INVALID_NO_VALUE
    const tidyStrings NON_MATCHING_ENDTAG
    const tidyStrings OBJECT_MISSING_ALT
    const tidyStrings OBSOLETE_ELEMENT
    const tidyStrings OPTION_REMOVED
    const tidyStrings OPTION_REMOVED_APPLIED
    const tidyStrings OPTION_REMOVED_UNAPPLIED
    const tidyStrings POTENTIAL_HEADER_BOLD
    const tidyStrings POTENTIAL_HEADER_ITALICS
    const tidyStrings POTENTIAL_HEADER_UNDERLINE
    const tidyStrings PREVIOUS_LOCATION
    const tidyStrings PROGRAMMATIC_OBJECTS_REQUIRE_TESTING_APPLET
    const tidyStrings PROGRAMMATIC_OBJECTS_REQUIRE_TESTING_EMBED
    const tidyStrings PROGRAMMATIC_OBJECTS_REQUIRE_TESTING_OBJECT
    const tidyStrings PROGRAMMATIC_OBJECTS_REQUIRE_TESTING_SCRIPT
    const tidyStrings PROPRIETARY_ATTRIBUTE
    const tidyStrings PROPRIETARY_ATTR_VALUE
    const tidyStrings PROPRIETARY_ELEMENT
    const tidyStrings REMOVED_HTML5
    const tidyStrings REMOVE_AUTO_REDIRECT
    const tidyStrings REMOVE_AUTO_REFRESH
    const tidyStrings REMOVE_BLINK_MARQUEE
    const tidyStrings REMOVE_FLICKER_ANIMATED_GIF
    const tidyStrings REMOVE_FLICKER_APPLET
    const tidyStrings REMOVE_FLICKER_EMBED
    const tidyStrings REMOVE_FLICKER_OBJECT
    const tidyStrings REMOVE_FLICKER_SCRIPT
    const tidyStrings REPEATED_ATTRIBUTE
    const tidyStrings REPLACE_DEPRECATED_HTML_APPLET
    const tidyStrings REPLACE_DEPRECATED_HTML_BASEFONT
    const tidyStrings REPLACE_DEPRECATED_HTML_CENTER
    const tidyStrings REPLACE_DEPRECATED_HTML_DIR
    const tidyStrings REPLACE_DEPRECATED_HTML_FONT
    const tidyStrings REPLACE_DEPRECATED_HTML_ISINDEX
    const tidyStrings REPLACE_DEPRECATED_HTML_MENU
    const tidyStrings REPLACE_DEPRECATED_HTML_S
    const tidyStrings REPLACE_DEPRECATED_HTML_STRIKE
    const tidyStrings REPLACE_DEPRECATED_HTML_U
    const tidyStrings REPLACING_ELEMENT
    const tidyStrings REPLACING_UNEX_ELEMENT
    const tidyStrings REPORT_MESSAGE_FIRST
    const tidyStrings REPORT_MESSAGE_LAST
    const tidyStrings SCRIPT_MISSING_NOSCRIPT
    const tidyStrings SCRIPT_NOT_KEYBOARD_ACCESSIBLE_ON_CLICK
    const tidyStrings SCRIPT_NOT_KEYBOARD_ACCESSIBLE_ON_MOUSE_DOWN
    const tidyStrings SCRIPT_NOT_KEYBOARD_ACCESSIBLE_ON_MOUSE_MOVE
    const tidyStrings SCRIPT_NOT_KEYBOARD_ACCESSIBLE_ON_MOUSE_OUT
    const tidyStrings SCRIPT_NOT_KEYBOARD_ACCESSIBLE_ON_MOUSE_OVER
    const tidyStrings SCRIPT_NOT_KEYBOARD_ACCESSIBLE_ON_MOUSE_UP
    const tidyStrings SKIPOVER_ASCII_ART
    const tidyStrings SPACE_PRECEDING_XMLDECL
    const tidyStrings STRING_ARGUMENT_BAD
    const tidyStrings STRING_CONTENT_LOOKS
    const tidyStrings STRING_DISCARDING
    const tidyStrings STRING_DOCTYPE_GIVEN
    const tidyStrings STRING_ERROR_COUNT
    const tidyStrings STRING_ERROR_COUNT_ERROR
    const tidyStrings STRING_ERROR_COUNT_WARNING
    const tidyStrings STRING_HELLO_ACCESS
    const tidyStrings STRING_HTML_PROPRIETARY
    const tidyStrings STRING_MISSING_MALFORMED
    const tidyStrings STRING_MUTING_TYPE
    const tidyStrings STRING_NEEDS_INTERVENTION
    const tidyStrings STRING_NOT_ALL_SHOWN
    const tidyStrings STRING_NO_ERRORS
    const tidyStrings STRING_NO_SYSID
    const tidyStrings STRING_PLAIN_TEXT
    const tidyStrings STRING_REPLACING
    const tidyStrings STRING_SPECIFIED
    const tidyStrings STRING_UNKNOWN_OPTION
    const tidyStrings STRING_XML_DECLARATION
    const tidyStrings STYLESHEETS_REQUIRE_TESTING_LINK
    const tidyStrings STYLESHEETS_REQUIRE_TESTING_STYLE_ATTR
    const tidyStrings STYLESHEETS_REQUIRE_TESTING_STYLE_ELEMENT
    const tidyStrings STYLE_SHEET_CONTROL_PRESENTATION
    const tidyStrings SUSPECTED_MISSING_QUOTE
    const tidyStrings TABLE_MAY_REQUIRE_HEADER_ABBR
    const tidyStrings TABLE_MAY_REQUIRE_HEADER_ABBR_NULL
    const tidyStrings TABLE_MAY_REQUIRE_HEADER_ABBR_SPACES
    const tidyStrings TABLE_MISSING_CAPTION
    const tidyStrings TABLE_MISSING_SUMMARY
    const tidyStrings TABLE_SUMMARY_INVALID_NULL
    const tidyStrings TABLE_SUMMARY_INVALID_PLACEHOLDER
    const tidyStrings TABLE_SUMMARY_INVALID_SPACES
    const tidyStrings TAG_NOT_ALLOWED_IN
    const tidyStrings TC_LABEL_COL
    const tidyStrings TC_LABEL_FILE
    const tidyStrings TC_LABEL_LANG
    const tidyStrings TC_LABEL_LEVL
    const tidyStrings TC_LABEL_OPT
    const tidyStrings TC_MAIN_ERROR_LOAD_CONFIG
    const tidyStrings TC_OPT_ACCESS
    const tidyStrings TC_OPT_ASCII
    const tidyStrings TC_OPT_ASHTML
    const tidyStrings TC_OPT_ASXML
    const tidyStrings TC_OPT_BARE
    const tidyStrings TC_OPT_BIG5
    const tidyStrings TC_OPT_CLEAN
    const tidyStrings TC_OPT_CONFIG
    const tidyStrings TC_OPT_ERRORS
    const tidyStrings TC_OPT_EXP_CFG
    const tidyStrings TC_OPT_EXP_DEF
    const tidyStrings TC_OPT_FILE
    const tidyStrings TC_OPT_GDOC
    const tidyStrings TC_OPT_HELP
    const tidyStrings TC_OPT_HELPCFG
    const tidyStrings TC_OPT_HELPENV
    const tidyStrings TC_OPT_HELPOPT
    const tidyStrings TC_OPT_IBM858
    const tidyStrings TC_OPT_INDENT
    const tidyStrings TC_OPT_ISO2022
    const tidyStrings TC_OPT_LANGUAGE
    const tidyStrings TC_OPT_LATIN0
    const tidyStrings TC_OPT_LATIN1
    const tidyStrings TC_OPT_MAC
    const tidyStrings TC_OPT_MODIFY
    const tidyStrings TC_OPT_NUMERIC
    const tidyStrings TC_OPT_OMIT
    const tidyStrings TC_OPT_OUTPUT
    const tidyStrings TC_OPT_QUIET
    const tidyStrings TC_OPT_RAW
    const tidyStrings TC_OPT_SHIFTJIS
    const tidyStrings TC_OPT_SHOWCFG
    const tidyStrings TC_OPT_UPPER
    const tidyStrings TC_OPT_UTF16
    const tidyStrings TC_OPT_UTF16BE
    const tidyStrings TC_OPT_UTF16LE
    const tidyStrings TC_OPT_UTF8
    const tidyStrings TC_OPT_VERSION
    const tidyStrings TC_OPT_WIN1252
    const tidyStrings TC_OPT_WRAP
    const tidyStrings TC_OPT_XML
    const tidyStrings TC_OPT_XMLCFG
    const tidyStrings TC_OPT_XMLERRS
    const tidyStrings TC_OPT_XMLHELP
    const tidyStrings TC_OPT_XMLOPTS
    const tidyStrings TC_OPT_XMLSTRG
    const tidyStrings TC_STRING_CHAR_ENCODING
    const tidyStrings TC_STRING_CONF_HEADER
    const tidyStrings TC_STRING_CONF_NAME
    const tidyStrings TC_STRING_CONF_NOTE
    const tidyStrings TC_STRING_CONF_TYPE
    const tidyStrings TC_STRING_CONF_VALUE
    const tidyStrings TC_STRING_FATAL_ERROR
    const tidyStrings TC_STRING_FILE_MANIP
    const tidyStrings TC_STRING_LANG_MUST_SPECIFY
    const tidyStrings TC_STRING_LANG_NOT_FOUND
    const tidyStrings TC_STRING_MISC
    const tidyStrings TC_STRING_MUST_SPECIFY
    const tidyStrings TC_STRING_OPT_NOT_DOCUMENTED
    const tidyStrings TC_STRING_OUT_OF_MEMORY
    const tidyStrings TC_STRING_PROCESS_DIRECTIVES
    const tidyStrings TC_STRING_UNKNOWN_OPTION
    const tidyStrings TC_STRING_UNKNOWN_OPTION_B
    const tidyStrings TC_STRING_VERS_A
    const tidyStrings TC_STRING_VERS_B
    const tidyStrings TC_STRING_XML
    const tidyStrings TC_TXT_HELP_1
    const tidyStrings TC_TXT_HELP_2A
    const tidyStrings TC_TXT_HELP_2B
    const tidyStrings TC_TXT_HELP_3
    const tidyStrings TC_TXT_HELP_3A
    const tidyStrings TC_TXT_HELP_CONFIG
    const tidyStrings TC_TXT_HELP_CONFIG_ALLW
    const tidyStrings TC_TXT_HELP_CONFIG_NAME
    const tidyStrings TC_TXT_HELP_CONFIG_TYPE
    const tidyStrings TC_TXT_HELP_ENV_1
    const tidyStrings TC_TXT_HELP_ENV_1A
    const tidyStrings TC_TXT_HELP_ENV_1B
    const tidyStrings TC_TXT_HELP_ENV_1C
    const tidyStrings TC_TXT_HELP_LANG_1
    const tidyStrings TC_TXT_HELP_LANG_2
    const tidyStrings TC_TXT_HELP_LANG_3
    const tidyStrings TEXT_ACCESS_ADVICE1
    const tidyStrings TEXT_ACCESS_ADVICE2
    const tidyStrings TEXT_BAD_FORM
    const tidyStrings TEXT_BAD_MAIN
    const tidyStrings TEXT_EQUIVALENTS_REQUIRE_UPDATING_APPLET
    const tidyStrings TEXT_EQUIVALENTS_REQUIRE_UPDATING_OBJECT
    const tidyStrings TEXT_EQUIVALENTS_REQUIRE_UPDATING_SCRIPT
    const tidyStrings TEXT_GENERAL_INFO
    const tidyStrings TEXT_GENERAL_INFO_PLEA
    const tidyStrings TEXT_HTML_T_ALGORITHM
    const tidyStrings TEXT_INVALID_URI
    const tidyStrings TEXT_INVALID_UTF16
    const tidyStrings TEXT_INVALID_UTF8
    const tidyStrings TEXT_M_IMAGE_ALT
    const tidyStrings TEXT_M_IMAGE_MAP
    const tidyStrings TEXT_M_LINK_ALT
    const tidyStrings TEXT_M_SUMMARY
    const tidyStrings TEXT_SGML_CHARS
    const tidyStrings TEXT_USING_BODY
    const tidyStrings TEXT_USING_FONT
    const tidyStrings TEXT_USING_FRAMES
    const tidyStrings TEXT_USING_LAYER
    const tidyStrings TEXT_USING_NOBR
    const tidyStrings TEXT_USING_SPACER
    const tidyStrings TEXT_VENDOR_CHARS
    const tidyStrings TEXT_WINDOWS_CHARS
    const tidyStrings TIDYCUSTOMBLOCKLEVEL_STRING
    const tidyStrings TIDYCUSTOMEMPTY_STRING
    const tidyStrings TIDYCUSTOMINLINE_STRING
    const tidyStrings TIDYCUSTOMNO_STRING
    const tidyStrings TIDYCUSTOMPRE_STRING
    const tidyStrings TIDYSTRINGS_FIRST
    const tidyStrings TIDYSTRINGS_LAST
    const tidyStrings TOO_MANY_ELEMENTS
    const tidyStrings TOO_MANY_ELEMENTS_IN
    const tidyStrings TRIM_EMPTY_ELEMENT
    const tidyStrings UNESCAPED_AMPERSAND
    const tidyStrings UNEXPECTED_ENDTAG
    const tidyStrings UNEXPECTED_ENDTAG_ERR
    const tidyStrings UNEXPECTED_ENDTAG_IN
    const tidyStrings UNEXPECTED_END_OF_FILE
    const tidyStrings UNEXPECTED_END_OF_FILE_ATTR
    const tidyStrings UNEXPECTED_EQUALSIGN
    const tidyStrings UNEXPECTED_GT
    const tidyStrings UNEXPECTED_QUOTEMARK
    const tidyStrings UNKNOWN_ELEMENT
    const tidyStrings UNKNOWN_ELEMENT_LOOKS_CUSTOM
    const tidyStrings UNKNOWN_ENTITY
    const tidyStrings USING_BR_INPLACE_OF
    const tidyStrings VENDOR_SPECIFIC_CHARS
    const tidyStrings WHITE_IN_URI
    const tidyStrings XML_DECLARATION_DETECTED
    const tidyStrings XML_ID_SYNTAX
