name: Build Manylinux Wheels

on:
  workflow_dispatch:
    inputs:

jobs:
  build_wheels:
    strategy:
      matrix:
        include:
          - os: windows-2022
            manylinux: notlinux
            archs: auto64
            name: windows
          - os: macos-12
            manylinux: notlinux
            archs: auto64
            name: macos
          - os: ubuntu-20.04
            manylinux: quay.io/pypa/manylinux2014_x86_64
            archs: auto
            name: manylinux2014
          - os: ubuntu-20.04
            manylinux: quay.io/pypa/manylinux_2_28_x86_64
            archs: auto
            name: manylinux_2_28

    name: Build ${{ matrix.os }} / ${{ matrix.manylinux }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: git config --global --add safe.directory '*' || true

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Update pip
        run: python3 -m pip install -U pip wheel setuptools

      - name: Install requirements
        run: python3 -m pip install -Ur requirements.txt

      - name: Cythonize
        run: make _pytidyhtml5.cpp

      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse-${{ matrix.os }}-${{ matrix.manylinux }}
        env:
          CIBW_SKIP: "cp27-* cp34-* cp35-* cp36-* pp*"  # FIXME: Unicode strings are broken in Pypy
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux }}
          CIBW_ARCHS: ${{ matrix.archs }}
          CIBW_BEFORE_BUILD: make clean-artifacts && make tidy-html5/build/cmake/libtidy.a
          CIBW_BUILD_FRONTEND: build
          CIBW_TEST_COMMAND: "{project}/basic-sanity-test.py"

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wheelhouse-${{ matrix.name }}
          path: ./wheelhouse*/*.whl
