name: Build Manylinux Wheels

on:
  workflow_dispatch:
    inputs:

jobs:
  build_wheels:
    strategy:
      matrix:
        os: ['windows-2019', 'macos-10.15']
        manylinux: ['notlinux']
        include:
          - os: ubuntu-20.04
            manylinux: manylinux2010
          - os: ubuntu-20.04
            manylinux: manylinux2014
          - os: ubuntu-20.04
            manylinux: manylinux_2_24

    name: Build ${{ matrix.os }} / ${{ matrix.manylinux }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Update pip
        run: python3 -m pip install -U pip wheel setuptools

      - name: Install requirements
        run: python3 -m pip install -Ur requirements.txt

      - name: Cythonize
        run: make _pytidyhtml5.cpp

      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse-${{ matrix.os }}-${{ matrix.manylinux }}
        env:
          CIBW_SKIP: "cp27-* cp34-* cp35-* pp*"  # FIXME: Unicode strings are broken in Pypy
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux }}
          CIBW_ARCHS: auto
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_BEFORE_BUILD: make clean-artifacts && make tidy-html5/build/cmake/libtidy.a
          CIBW_BUILD_FRONTEND: pip
          CIBW_TEST_COMMAND: "{project}/basic-sanity-test.py"

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wheelhouse-${{ matrix.os }}-${{ matrix.manylinux }}
          path: ./wheelhouse-${{ matrix.os }}-${{ matrix.manylinux }}/*.whl
